server:
  port: 8888

spring:
  application:
    name: demo1
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://cdb-jgo579l6.cd.tencentcdb.com:10051/my-spring?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&useSSL=false
    username: root
    password: gaoyu#502

    hikari:
      data-source-properties:
        nested-transaction-allowed: true

  #    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
  mvc:
    throw-exception-if-no-handler-found: true
  redis:
    database: 0
    host: 172.20.2.141
    port: 6379
    password: 0Huhg34vMyitUmTg4zWC
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
#  data:
#    mongodb:
#      uri: mongodb://baic-bccp:tima123@172.20.2.143:27017/baic-vehicle-snapshot?ssl=false&authMechanism=SCRAM-SHA-1

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.example.demo1.entity
  type-handlers-package: com.example.demo1.config

logging:
  level:
    root: debug
    com.example.demo1: debug
